### ISSUE TITLE
Change in usermodel breaks models that previously ran without issues

### ISSUE THREAD

**Issue by joellepasman** [GenomicSEM/GenomicSEM#86]
I updated the package last week and suddenly models that ran without issues previously now no longer converge. I've encountered issues with 3 unrelated models now (in 2 different datasets) and I don't see why these in particular would suddenly not converge. I think the recent update in usermodel is causing the trouble. Did some default behaviors change? I'd be happy to use an old version but I can't find previous code releases.

**Comment by MichelNivard** [comment]
Hi Joelle I think Andrew was already in touch on the google group, If you want to drop down a version or two you cna always do that here: https://github.com/GenomicSEM/GenomicSEM/commits/master/  and clicking the commit details which should move you to that version. You then also have to drop down versions of lavaan in this case i think because they changed stuff on their end... (I'd just not update in a project unless you have too really, then you never have these kinds off issues). For specific help with the specific model, or to help us speed up solving this for you send a reproducible error example to Andrew trough the ongoingconvo in the google group
<img width="237" alt="image" src="https://github.com/user-attachments/assets/89643933-88fc-4b02-bb51-e0301099c39c">

**Comment by joellepasman** [comment]
Thanks Michel, I reverted back to these versions, which solved my issues:
devtools::install_github("GenomicSEM/GenomicSEM@4650dec90fce9985d566b8a5f9ff89abd6762632")
devtools::install_version("lavaan", version = "0.6-18", repos = "http://cran.us.r-project.org")

**Comment by MichelNivard** [comment]
Awesome, ideally you'd always lock in a version for one single project, our dependency on lavaan means we can't always control these things across versions etc.
